### ISSUE TITLE
 How can a user get the replies he has sent to the message sender ?

### ISSUE THREAD

**Issue by craftcmscoder** [blue-mantis/BM-Private-Messaging#2]
Through this plugin I'm trying to make a message box like twitter, where messages are grouped by user and there is history of all message exchanged between logged in user and any other user,  Is there any way through which i could get the replies which i have sent to the message sender ?

**Comment by auralon** [comment]
Hi @craftcmscoder, the plugin doesn't currently have this functionality.  It would be simple enough to add in... you'd want to add in a method to `services/PrivateMessaging_MessagesService.php`, something like `getSentMessages`

    public function getSentMessages() {
	    if (!craft()->userSession || !craft()->userSession->getUser()) return [];

	    $userId = craft()->userSession->getUser()->id;

	    $records = PrivateMessaging_MessageRecord::model()->findAllByAttributes(['senderId' => $userId], ['order' => 'id DESC']);

	    return $records;
    }

I haven't had chance to test this, so you'll want to do so before pushing this code to any sort of production system!

When I get a chance to test it, I shall add in this functionality.

**Comment by auralon** [comment]
You'd need to add a line into the twigextension too.  I've added this to the dev branch... https://github.com/blue-mantis/BM-Private-Messaging/tree/dev

If you grab the code there and give it a test (I still haven't had chance).

Hopefully that will work do the trick for you! :)

**Comment by craftcmscoder** [comment]
Thanks @auralon . Will Give it a try !!

**Comment by auralon** [comment]
No worries.  If you have any trouble, please let me know and I'll try to help out.
