### ISSUE TITLE
Craft 3 support

### ISSUE THREAD

**Issue by arifje** [blue-mantis/BM-Private-Messaging#7]
Would be nice.

**Comment by georgejr** [comment]
Oh yes!

**Comment by kinoli** [comment]
I third the request!

**Comment by auralon** [comment]
Hi folks, sorry for the slow response.  I've discussed this in the office and we'd certainly like to port this over. It's simply a case of finding the time to do so!  If and when this gets ported, I'll be sure to let you know.

**Comment by arifje** [comment]
Any update on this? 

Maybe we can speed it up it we make some budget available? Let me know, thanks!

**Comment by auralon** [comment]
@skoften That would certainly put this on the radar.  Right now we're extremely busy with paid work, so scheduling this port in takes a back seat, but if there was budget, then we could prioritise it.

**Comment by arifje** [comment]
Awesome, can I contact you by mail?

**Comment by auralon** [comment]
Sure thing, you can ping an email over to...

`hello [at] bluemantis [dot] com`

**Comment by engram-design** [comment]
@auralon Not sure of your immediate plans, but we're halfway through developing a similar system. Just wanted to check in on your roadmap?

**Comment by auralon** [comment]
@engram-design We've just recently released the Craft 3 version of this plugin, which includes threading functionality.  It can be found [here](https://github.com/blue-mantis/craft-private-messaging).

**Comment by engram-design** [comment]
Cool, thanks!
